DROP TABLE "Parent Section";
DROP TABLE "Historique";
DROP TABLE "Invited";
DROP TABLE "Redaction";
DROP TABLE "Paragraphe";
DROP TABLE "Story";
DROP TABLE "User";

DROP SEQUENCE "USER_USER_ID_SEQ";
DROP SEQUENCE "STORY_STORY_ID_SEQ";
DROP SEQUENCE "PARAGRAPHE_PARA_ID_SEQ";
DROP SEQUENCE "HISTORIQUE_HISTORIC_ID_SEQ";